### ISSUE TITLE
Graphical Timetables

### ISSUE THREAD

**Issue by LinqToException** [LinqToException/VirTracks#15]
Using the existing data, adding a graphical timetable would be neat.

![image](https://github.com/LinqToException/VirTracks/assets/47725963/04cd2879-eeb9-4bbc-9510-ce3bdf22d69d)

A few questions remain:

- Where would this be displayed?
  - A dedicated page where you can select stations, and the graph is displayed for these stations in that order? Can you save your selection/preset? Do we offer "filters" for these stations (i.e. if you select station A, then the only stations you can select now are stations that have one train passing from A to there?)
  - I think it would be nice if, on the dispatch view, you could get a view for the next station (on hovering over a "from" or "to" cell). This could help with stations that have a single line between them.
- Do we just display live data, or live data and timetable data?
- How do we deal with delays? Do they propagate across stops? Do layovers "eat" delay time?
- What's the time range? Is this adjustable? Is it fixed to now +/- some delay? Configurable?

**Comment by DazrahT** [comment]
A further question for you to ponder:

Ability to change Axis so time runs on X, and stations on Y axis.

**Comment by LinqToException** [comment]
That's probably not going to happen, because drawing the graph is super-annoying as-is, and switching axes would, uh... not improve matters.
