### ISSUE TITLE
Show AI-only stations on the map

### ISSUE THREAD

**Issue by matejdro** [LinqToException/VirTracks#20]
Any chance you could add AI only stations to the map, the ones that are displayed as small orange symbol on the original map:

![image](https://github.com/LinqToException/VirTracks/assets/507922/f5d38c21-5c2e-43a0-a032-96912285ec04)

That would make it much easier to judge distances from controller's station to the next station (which may or may not be AI only).

**Comment by LinqToException** [comment]
Hello!

I've actually been thinking about this for a while. My use-to case is Kozlow, which I would sometimes really like to see the departures for (especially when dispatching Psary).

Currently, I'm using the API data for stations to place them on the map - this data isn't available for non-playable stations, hence why they are missing on the map (and in-game). It should be possible, however, to "fake" this for missing stations by simply taking the average position of all signals I think. With the exception of Psary, this should work ~okay-ish until we get official data.

I'll add it to my list - but it should be one of the more easily doable things.

**Comment by LinqToException** [comment]
Added in v2.6.0.
