### ISSUE TITLE
EDR sorting order after 2300hrs until midnight

### ISSUE THREAD

**Issue by DazrahT** [LinqToException/VirTracks#22]
At present, as you approach 23:00hrs when using the EDR the sorting order of trains is all over the place for trains that are booked to arrive/depart after midnight which appear randomly in the middle of the 23:00 - 23:59 departures, rather than flowing top to bottom in timetable order (ie, the should appear at the bottom as a new day)

So these ones highlighted shouldn't be there as it creates a gap between train(s) that have arrived (green highlight) and those approaching (yellow highlight)

![image](https://github.com/LinqToException/VirTracks/assets/134434694/c5ff0f2d-8f42-4d7d-8ad9-eb2e80e2309e)

**Comment by LinqToException** [comment]
Midnight handling is something that the application struggles with in various places. Although I'm not entirely sure why it's _this_ bad - usually it popped them at the bottom or the top.

What are your sort settings?

**Comment by DazrahT** [comment]
Sort by ETA
