### ISSUE TITLE
Feature request: EDR auto-scroll to active train(s)

### ISSUE THREAD

**Issue by DazrahT** [LinqToException/VirTracks#23]
Seeing as the EDR currently highlights trains, would it be possible to make the EDR scroll automatically?

It would be nice so that the first highlighted (active) train at your station as being tthe top row and then as trains depart the EDR then automatically scrolls the page to whatever is the next active train.

If there are no active trains, scroll to whatever train is next by ETA / Next booked to arrive (Depending if you're sorting by ETA mode or not)

It would be a great help as a lot of time is spent just scrolling the page to keep whatever trains I'm looking at in the right place!

**Comment by LinqToException** [comment]
In theory, I suppose - practically, there's some UX issues that arise:

- How can you turn this behaviour on/off?
- If I do scroll manually (e.g. to look at a previous/incoming train), does this disable the scrolling? Or will it force-scroll me again once the next train update arrives?

I can't say I have this issue when I'm playing - but I usually keep the time frame relatively short to avoid having too many trains on the screen anyway. Is there a particular station where this is usually an issue?

**Comment by DazrahT** [comment]
I usually have my visibility time set for 90 minutes so I can see a bit further afield.

As for turning auto-scroll on/off, perhaps a button/check box?
