### ISSUE TITLE
Feature request: Ability for filter EDR by direction / next / previous location

### ISSUE THREAD

**Issue by DazrahT** [LinqToException/VirTracks#25]
Would it be possibly to allow the EDR to be sorted by direction / filters?

If possibly the default should be "off", but from the main EDR page then allow some sort of sorting options, and example could be at Zawiercie, show me all trains where the next location in the timetable is Lazy La (and that'll show you most if not all trains in the southbound direction)

Another option would be at Location X (X being whichever location you're currently looking at), show me all trains that have come from Y.

**Comment by LinqToException** [comment]
I was thinking about this, but the question kind of was "What for?". Like, assuming you filter for La - you're missing half the trains. Is this filter something you're changing frequently, or something that you do once? Do you have multiple instances of VirTracks open then, one per direction?

**Comment by DazrahT** [comment]
I was thinking something that could be used 'on the fly' rather than permanent.

So for example last night I was on Opocno and I was sneaking trains through towards Olszamowice, so I changed my EDR to Olszamowice, to see the ETA of the trains I intended on sending, it then dawned on me "Wouldn't it be useful if there was a filter that could only show trains from Op" (It's something I actually use quite a lot at work with our computer system, not web based, its an IBM mainframe system from the 1970s, and that has it!)
